### ISSUE TITLE
no database file

### ISSUE THREAD

**Issue by guhan93** [syedkamran124/GYM-MANAGEMENT#1]
please provide sql(database) file

**Comment by syedkamran124** [comment]
I will upload it by tomorrow

**Comment by guhan93** [comment]
thank you.

**Comment by guhan93** [comment]
as soon as you upload i'll close the comment

**Comment by syedkamran124** [comment]
Ok

**Comment by guhan93** [comment]
please upload the datatbase file

**Comment by syedkamran124** [comment]
I will upload it by today for sure

**Comment by syedkamran124** [comment]
What?

**Comment by syedkamran124** [comment]
I have uploaded the database file....please check it...and do follow me i
will follow you back...thank you

**Comment by guhan93** [comment]
thank you

**Comment by syedkamran124** [comment]
Open the project and in the project i have created a database file folder
open that folder in that folder you will find the sql file

**Comment by syedkamran124** [comment]
Oh sorry i don't read your message....i think you can't find the
file....you said thank you....and you are most welcome🙂
