### ISSUE TITLE
database file not found

### ISSUE THREAD

**Issue by dhanushkannan11** [syedkamran124/GYM-MANAGEMENT#2]
kindly upload the sql file !!
how to create admin login ?

**Comment by syedkamran124** [comment]
I will upload it database file by today....and import that database file in
your sql and check the name email and password in sql if you want to change
the data just change it and then finally run admin.html, login by giving
the values and then you will access the admin login

**Comment by dhanushkannan11** [comment]
thank you :)

**Comment by syedkamran124** [comment]
I have uploaded the database file...please check it...and please do follow
me i will follow you back...thank you
